---
title: "R Notebook"
output: html_notebook
---

My version of the Monty Hall problem - details on https://en.wikipedia.org/wiki/Monty_Hall_problem.

First set up a function to represent one run through a simulation:

```{r}
sim <- function() {
    # Set up the three doors, one of which wins a car
    doors <- c('1','2','3')
    car <- sample(doors,1)
    
    # The contestant guesses one of the doors
    guess <- sample(doors,1)
    
    # The host shows one of the other doors (that's not the correct one)
    remaining_doors <- doors[doors != car & doors != guess]
    shown <- sample(remaining_doors,1)
    
    # Try not swapping and record if successful?
    guess <- guess
    if(guess == car) {
        not_swap_successes <<- not_swap_successes + 1
    }
    
    # Then try swapping and record if successful
    guess <- sample(doors[doors != guess & doors != shown],1)
    if(guess == car) {
        swap_successes <<- swap_successes + 1
    }
}
```

Run 10,000 simulations

```{r}
# Set up success and failure counts
not_swap_successes <- 0
swap_successes <- 0

n <- 10000
for(i in 1:n) {
    sim()
}
print("Done!")
```

And report back findings!

```{r}
print(paste("Not swap successes:",not_swap_successes))
print(paste("Swap successes:",swap_successes))
```

As expected, swapping (2/3 chance of success) is about twice as successful as not swapping (1/3 chance of success)